### ISSUE TITLE
multiple select behaviour [feature request]

### ISSUE THREAD

**Issue by zassq** [Voral/vs-vue3-select#2]
Hi, thanks for the nice lib!

Just wondering if you can add some features for MULTIPLE select like:
1. Instead of closing the option drop down on selecting an option, leave it open when multiple is activated. Maybe use click outside to close the option drop down.
2. Deselecting by clicking on a selected value, instead of the 'X' button

Or maybe some setting options to choose the behaviour.

Thank you.

**Comment by Voral** [comment]
Good idea. I'll work on it.

**Comment by Voral** [comment]
I'm sorry, I didn't read it carefully.  I hurried to write a previous comment

There is already such an opportunity. Pay attention to the [closeOnSelect](https://vue3-select.va-soft.ru/api/props/#closeonselect) parameter.  In combination with the multiple parameter, it gives the result you want.

`
<v-select 
        multiple
        :options="['test1', 'test2']"
        :closeOnSelect="false" 
/>
`
