### ISSUE TITLE
multiple select: 'x' hidden

### ISSUE THREAD

**Issue by seth-setiadha** [Voral/vs-vue3-select#3]
Hey,

I'm curious if anyone has the same experience as mine. For multiple select, the close 'x' button is hidden. Is there a tweak to fix this?
![image](https://github.com/Voral/vs-vue3-select/assets/2004326/8df65bdd-e2c3-4543-bfb8-ca460f2acca8)

**Comment by Voral** [comment]
Yes, this is true for long values. The button goes out of sight.  Obviously, it is necessary for vs__deselect to apply absolute positioning and value overlap.  I'll think about it

**Comment by Voral** [comment]
Fixed in version 1.3.6
